### ISSUE TITLE
New project template download fails on slow connection

### ISSUE THREAD

**Issue by senoadiw** [expo/xde#112] opened 2017-05-14 14:30 UTC
Hello,

I sometimes am limited to a slow 1 mbps internet connection, when creating a new project in Windows the template download fails half-way even though it was progressing steadily at full 1 mbps speed (120 kBps).

![image](https://cloud.githubusercontent.com/assets/1198399/26034507/d370a760-38e7-11e7-90cd-7dfdd3c21b16.png)

Checking C:\Users\userdir\\.expo\starter-app-cache\ there is the an incomplete 50MB file named blank-16.0.1.tar.gz

Sometimes at 80%

![image](https://cloud.githubusercontent.com/assets/1198399/26034778/ead10f2c-38eb-11e7-85de-b81725fa1320.png)

If I don't click retry it returns with the following error:

![image](https://cloud.githubusercontent.com/assets/1198399/26034556/abc23b60-38e8-11e7-9b5b-b27ffa18091b.png)

Clicking Create, the downloading project files spinner appears and then goes back with the following error:

EPERM: operation not permitted, access 'C:\Users\userdir\\.expo\starter-app-cache\blank-16.0.1.tar.gz'

I need to restart XDE to initiate the download process again and get the same issue as above.

Platform: Win 7 Enterprise SP1 64 bit

Installer: xde-Setup-2.18.0.exe

Cheers

**Comment by wedranb** [comment] 2017-05-29 16:42
Same issue here... Win 10.

**Comment by brentvatne** [comment] 2017-05-29 19:40
@charlesvinette - can you take a look at this? not sure why it impacts windows specifically

**Comment by charlesvinette** [comment] 2017-05-29 19:48
Of course, will look into it!

**Comment by charlesvinette** [comment] 2017-06-05 22:08
Hello @wedranb @senoadiw. I looked into this issue and I can confirm that at no point we are cancelling the download, no matter the rate at which it is going. However, I saw that the Request library we are using is actually causing the error you are getting, intermittently.

The good news is that we've worked on transitioning from Request to Axios, another networking library that should make the XDE more reliable. Should be out pretty soon!

**Comment by markwk** [comment] 2017-06-07 06:00
Same issue here. It's giving me slow connection warnings and eventually timing out / failing. First time user of Expo and kind of a rough start when you can't install for initial project. I can use npm fine for other react-native work. So not quite sure what the issue is.

**Comment by brentvatne** [comment] 2017-06-09 19:30
The fix for this issue is being tracked here, it will be available in our next XDE release: https://github.com/expo/expo/issues/179

**Closed by brentvatne** 2017-06-09 19:30 UTC
