### ISSUE TITLE
Getting prompt to "Please fill out all the fields" even when all fields are filled

### ISSUE THREAD

**Issue by abhitheawesomecoder** [expo/xde#146] opened 2017-10-26 04:25 UTC
getting stuck at the screen attached
![expoerror](https://user-images.githubusercontent.com/3944526/32034982-bcb21b62-ba33-11e7-8672-a728efb1fc2e.png)

**Comment by ide** [comment] 2017-10-26 07:30
@abhitheawesomecoder Thanks for the bug report! Our authentication provider that we use for developer accounts is actually experiencing a critical issue right now so we've disabled login until the issue is fixed. I'm really sorry about that.

@jimmylee Assuming this is related to the Auth0 outage, we probably should show a more accurate error message here.

**Comment by ide** [comment] 2017-10-26 07:35
We keep issues related to Expo on the repo for "expo" so I've recreated your report over here: https://github.com/expo/expo/issues/857 and am going to close this one.

**Closed by ide** 2017-10-26 07:35 UTC
